#!/bin/bash
    docker -version

    if [$? -eq 0]
        then
        echo \"[Docker já instalado]\"
        sleep 3
    else
        echo \"[Docker ainda não instalado...]\"
        sleep 3

        echo \"[Preparando para iniciar instalação....Instalando Docker...]\"
            echo 
            sudo apt update 
            sleep 4

            sudo apt install docker.io -y
            sleep 4
            
            sudo systemctl start docker
            sudo systemctl enable docker

          sudo docker pull mysql:8
            sleep 4
            sudo docker run -d -p 3306:3306 --name ContainerMySql -e "MYSQL_DATABASE=isee" -e "MYSQL_ROOT_PASSWORD=urubu100" mysql:8
            echo \"[Criando Container de MySql...Acessando o Container...]\"
            sleep 2
            
            sudo docker exec -it ContainerMySql bash
            mysql -u root -p
            urubu100
            sleep 1
            
            source ./bancodedados-isee-v3.sql
            sleep 3
            exit
            echo \"[Imagem de MySQL em Container Docker instalada...e tabelas mySQL criadas]\"
            sleep 3
    fi
