version: '3.6'

  services:
    db:
      image: mysql:8.0
      container_name: ContainerMySql
      environment:
        MYSQL_ROOT_PASSWORD: urubu100
        MYSQL_DATABASE: isee
        MYSQL_USER: root
        MYSQL_PASSWORD: urubu100
      ports:
        - "8081:3306"
      volumes:
        - dbdata:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
          - 3306:3306
  volumes:
    dbdata:
